global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'taxapp'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'taxapp'
          environment: 'dev'
      - targets: ['host.docker.internal:8081']
        labels:
          service: 'taxapp'
          environment: 'prod'